language: node_js
node_js:
  - 4.1

env:
    - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

notifications:
  slack: armvisualizer:${slack_notification_key}

before_script:
  - npm install -g gulp bower typings typescript
  - bower install
  - typings install
script: gulp
branches:
  only:
    - master

deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
