language: node_js
node_js:
  - 0.12
  
notifications:
  slack: armvisualizer:${slack_notification_key}
  
before_script:
  - npm install -g gulp bower tsd typescript
  - bower install
  - tsd install
script: gulp
branches:
  only:
    - master
    
deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master